### ISSUE TITLE
Update DNS to point to Netlify

### ISSUE THREAD

**Issue by rosnovsky** [datasquadron/datasquadron.github.io#7]
We need to add an A-record:

`datasquadron.com A 104.198.14.52`

or create an ALIAS (may not be supported)

`datasquadron.com ALIAS datasquadron.netlify.com.`

**Comment by bawbgale** [comment]
A record done for datasquadron.com. Waiting for CNAME for www to propagate.

**Comment by rosnovsky** [comment]
Done! We now even have SSL :)
